"""GM (1996+) vehicle profile.

J1850 VPW pre-2008, CAN 2008+ — the ELM327's protocol auto-detect handles
the difference transparently, so this profile (and cypher_dds.core) applies
unchanged across the whole range. Priority 1 target — standard-heavy,
well-documented enhanced PIDs available in the aftermarket scanner
community. Tables below are seeds; expand as documentation is gathered.
"""

from __future__ import annotations

from cypher_dds.profiles.base import EnhancedPID, VehicleProfile, register_profile

# GM manufacturer-specific (P1xxx) DTC definitions, sourced from public
# OBD-II reference documentation. Covers 1996+ GM platforms; exact wording
# can vary slightly by model year/family since GM has reused some code
# numbers for different faults across platforms (noted with "/" where the
# source material showed more than one definition for the same code).
# TODO: expand with B/C/U-series GM codes and enhanced (Mode 22) PIDs.
DTC_TABLE: dict[str, str] = {
    # Oxygen sensors / HO2S
    "P1031": "HO2S Heater Current Monitor Control Circuit Banks 1 and 2 Sensor 1",
    "P1032": "HO2S Heater Warm Up Control Circuit Banks 1 and 2 Sensor 1",
    "P1130": "HO2S Circuit Low Variance Bank 1 Sensor 1",
    "P1131": "HO2S Circuit Low Variance Bank 1 Sensor 2",
    "P1132": "HO2S Circuit Low Variance Bank 2 Sensor 1",
    "P1133": "HO2S Insufficient Switching Bank 1 Sensor 1",
    "P1134": "HO2S Transition Time Ratio Bank 1 Sensor 1",
    "P1135": "HO2S Lean Mean Bank 1 Sensor 1",
    "P1136": "HO2S Rich Mean Bank 1 Sensor 1",
    "P1137": "HO2S Bank 1 Sensor 2 Lean System or Low Voltage",
    "P1138": "HO2S Bank 1 Sensor 2 Rich or High Voltage",
    "P1139": "HO2S Insufficient Switching Bank 1 Sensor 2",
    "P1140": "HO2S Transition Time Ratio Bank 1 Sensor 2",
    "P1141": "HO2S Heater Control Circuit Bank 1 Sensor 2",
    "P1143": "HO2S Bank 1 Sensor 3 Lean System or Low Voltage",
    "P1144": "HO2S Bank 1 Sensor 3 Rich or High Voltage",
    "P1145": "HO2S Cross Counts Bank 1 Sensor 3",
    "P1153": "HO2S Insufficient Switching Bank 2 Sensor 1",
    "P1154": "HO2S Transition Time Ratio Bank 2 Sensor 1",
    "P1155": "HO2S Lean Mean Bank 2 Sensor 1",
    "P1156": "HO2S Rich Mean Bank 2 Sensor 1",
    "P1157": "HO2S Bank 2 Sensor 2 Lean System or Low Voltage",
    "P1158": "HO2S Bank 2 Sensor 2 Rich or High Voltage",
    "P1159": "HO2S Cross Counts Bank 2 Sensor 2",
    "P1161": "HO2S Heater Control Circuit Bank 2 Sensor 2",
    "P1163": "HO2S Bank 2 Sensor 3 Lean System or Low Voltage",
    "P1164": "HO2S Bank 2 Sensor 3 Rich or High Voltage",
    "P1165": "HO2S Cross Counts Bank 2 Sensor 3",
    "P1170": "Bank to Bank Fuel Trim Offset",
    "P1171": "Fuel System Lean During Acceleration",
    # Sensors: MAP, IAT, ECT, TP, MAF
    "P1105": "Secondary Vacuum Sensor Circuit",
    "P1106": "Manifold Absolute Pressure (MAP) Sensor Circuit Intermittent High Voltage",
    "P1107": "Manifold Absolute Pressure (MAP) Sensor Circuit Intermittent Low Voltage",
    "P1108": "BARO to MAP Sensor Comparison Too High",
    "P1109": "Secondary Port Throttle System",
    "P1111": "Intake Air Temperature (IAT) Sensor Circuit Intermittent High Voltage",
    "P1112": "Intake Air Temperature (IAT) Sensor Circuit Intermittent Low Voltage",
    "P1113": "Intake Resonance Switchover Solenoid Control Circuit",
    "P1114": "Engine Coolant Temperature (ECT) Sensor Circuit Intermittent Low Voltage",
    "P1115": "Engine Coolant Temperature (ECT) Sensor Circuit Intermittent High Voltage",
    "P1116": "ECT Signal Unstable or Intermittent",
    "P1117": "Engine Coolant Temp. Signal Out-Of-Range Low",
    "P1118": "Engine Coolant Temp. Signal Out-Of-Range High",
    "P1119": "ECT Signal Out-Of-Range With TFT Sensor",
    "P1120": "Throttle Position (TP) Sensor 1 Circuit",
    "P1121": "Throttle Position (TP) Sensor Circuit Intermittent High Voltage",
    "P1122": "Throttle Position (TP) Sensor Circuit Intermittent Low Voltage",
    "P1125": "APP System",
    "P1185": "Engine Oil Temperature Circuit",
    "P1186": "EOT Circuit Performance",
    "P1187": "EOT Sensor Circuit Low Voltage",
    "P1188": "EOT Sensor Circuit High Voltage",
    "P1189": "Engine Oil Pressure (EOP) Switch Circuit",
    "P1190": "Engine Vacuum Leak",
    "P1191": "Intake Air Duct Air Leak",
    "P1211": "Mass Air Flow Circuit Intermittent High",
    "P1212": "Mass Air Flow Circuit Intermittent Low",
    "P1219": "Throttle Position Sensor Reference Voltage",
    "P1220": "Throttle Position (TP) Sensor 2 Circuit",
    "P1450": "Barometric Pressure Sensor Circuit",
    "P1451": "Barometric Pressure Sensor Performance",
    # Fuel / injectors
    "P1200": "Injector Control Circuit",
    "P1201": "(Alt. Fuel) Gas Mass Sensor Circuit Range/Performance",
    "P1202": "(Alt. Fuel) Gas Mass Sensor Circuit Low Frequency",
    "P1203": "(Alt. Fuel) Gas Mass Sensor Circuit High Frequency",
    "P1214": "Injection Pump Timing Offset",
    "P1215": "Ground Fault Detection Indicated",
    "P1216": "Fuel Solenoid Response Time Too Short",
    "P1217": "Fuel Solenoid Response Time Too Long",
    "P1218": "Injection Pump Calibration Circuit",
    "P1221": "Fuel Pump Secondary Circuit Low",
    "P1222": "Injector Control Circuit Intermittent",
    "P1225": "Injector Circuit Cylinder 2 Intermittent",
    "P1228": "Injector Circuit Cylinder 3 Intermittent",
    "P1231": "Injector Circuit Cylinder 4 Intermittent",
    "P1234": "Injector Circuit Cylinder 5 Intermittent",
    "P1237": "Injector Circuit Cylinder 6 Intermittent",
    "P1240": "Injector Circuit Cylinder 7 Intermittent",
    "P1243": "Injector Circuit Cylinder 8 Intermittent",
    "P1245": "Intake Plenum Switchover Valve",
    "P1250": "Early Fuel Evaporation Heater Circuit",
    "P1257": "Supercharger System Overboost",
    "P1258": "Engine Coolant Overtemperature - Protection Mode Active",
    "P1431": "Fuel Level Sensor 2 Circuit Performance",
    "P1432": "Fuel Level Sensor 2 Circuit Low Voltage",
    "P1433": "Fuel Level Sensor 2 Circuit High Voltage",
    # Accelerator pedal position
    "P1270": "Accelerator Pedal Position Sensor A/D Converter Error",
    "P1271": "Accelerator Pedal Position (APP) Sensor 1-2 Correlation",
    "P1272": "Accelerator Pedal Position Sensor 2",
    "P1273": "Accelerator Pedal Position Sensor 1",
    "P1274": "Injectors Wired Incorrectly",
    "P1275": "Accelerator Pedal Position (APP) Sensor 1 Circuit",
    "P1276": "Accelerator Pedal Position Sensor 1 Circuit Performance",
    "P1277": "Accelerator Pedal Position Sensor 1 Circuit Low Voltage",
    "P1278": "Accelerator Pedal Position Sensor 1 Circuit High Voltage",
    "P1280": "Accelerator Pedal Position (APP) Sensor 2 Circuit",
    "P1281": "Accelerator Pedal Position Sensor 2 Circuit Performance",
    "P1282": "Accelerator Pedal Position Sensor 2 Circuit Low Voltage",
    "P1283": "Accelerator Pedal Position Sensor 2 Circuit High Voltage",
    "P1285": "Accelerator Pedal Position Sensor 3 Circuit",
    "P1286": "Accelerator Pedal Position Sensor 3 Circuit Performance",
    "P1287": "Accelerator Pedal Position Sensor 3 Circuit Low Voltage",
    "P1288": "Accelerator Pedal Position Sensor 3 Circuit High Voltage",
    # Ignition system
    "P1300": "Ignitor Circuit",
    "P1305": "Ignition Coil 2 Primary Feedback Circuit",
    "P1310": "Ignition Coil 3 Primary Feedback Circuit",
    "P1315": "Ignition Coil 4 Primary Feedback Circuit",
    "P1320": "IC 4X Reference Circuit Intermittent",
    "P1321": "Electronic Ignition System Fault Line",
    "P1322": "EI System or Ignition Control Extra or Missing",
    "P1323": "IC 24X Reference Circuit Low Frequency",
    "P1324": "Crank RPM Too Low",
    "P1335": "CKP Circuit",
    "P1336": "Crankshaft Position (CKP) System Variation Not Learned",
    "P1345": "Crankshaft Position (CKP)-Camshaft Position (CMP) Correlation",
    "P1346": "Intake Camshaft Position (CMP) Sensor System Performance",
    "P1350": "Ignition Control System",
    "P1351": "Ignition Coil Control Circuit High Voltage",
    "P1352": "IC Output High/Pulse Detected when GND Cyl. 2",
    "P1353": "IC Output High/Pulse Detected when GND Cyl. 3",
    "P1354": "IC Output High/Pulse Detected when GND Cyl. 4",
    "P1355": "IC Output High/Pulse Detected when GND Cyl. 5",
    "P1356": "IC Output High/Pulse Detected when GND Cyl. 6",
    "P1357": "IC Output High/Pulse Detected when GND Cyl. 7",
    "P1358": "IC Output High/Pulse Detected when GND Cyl. 8",
    "P1359": "Ignition Coil Group 1 Control Circuit",
    "P1360": "Ignition Coil Group 2 Control Circuit",
    "P1361": "Ignition Coil Control Circuit Low Voltage",
    "P1362": "IC Cylinder 2 Not Toggling After Enable",
    "P1363": "IC Cylinder 3 Not Toggling After Enable",
    "P1364": "IC Cylinder 4 Not Toggling After Enable",
    "P1365": "IC Cylinder 5 Not Toggling After Enable",
    "P1366": "IC Cylinder 6 Not Toggling After Enable",
    "P1367": "IC Cylinder 7 Not Toggling After Enable",
    "P1368": "IC Cylinder 8 Not Toggling After Enable",
    "P1370": "IC 4X Reference Circuit Too Many Pulses",
    "P1371": "IC 4X Reference Circuit Too Few Pulses",
    "P1372": "Crankshaft Position (CKP) Sensor A-B Correlation",
    "P1374": "3X Reference Circuit",
    "P1375": "IC 24X Reference Circuit High Voltage",
    "P1376": "Ignition Ground Circuit",
    "P1377": "IC Cam Pulse To 4X Reference Pulse",
    "P1380": "Misfire Detected - Rough Road Data Not Available",
    "P1381": "Misfire Detected - No Communication with Brake Control Module",
    "P1602": "Knock Sensor (KS) Module Performance",
    # Wheel speed sensors (ABS-adjacent, still reported via powertrain PCM on some platforms)
    "P1390": "Wheel Speed Sensor 1 - G - Sensor Circuit",
    "P1391": "Wheel Speed Sensor 1 - G - Sensor Circuit Performance",
    "P1392": "Wheel Speed Sensor 1 - G - Sensor Circuit Low Voltage",
    "P1393": "Wheel Speed Sensor 1 - G - Sensor Circuit High Voltage",
    "P1394": "Wheel Speed Sensor 1 - G - Sensor Circuit Intermittent",
    "P1395": "Wheel Speed Sensor 2 - G - Sensor Circuit",
    "P1396": "Wheel Speed Sensor 2 - G - Sensor Circuit Performance",
    "P1397": "Wheel Speed Sensor 2 - G - Sensor Circuit Low Voltage",
    "P1398": "Wheel Speed Sensor 2 - G - Sensor Circuit High Voltage",
    "P1399": "Wheel Speed Sensor 2 - G - Sensor Circuit Intermittent",
    # EGR / secondary air / EVAP
    "P1403": "Exhaust Gas Recirculation System Valve 1",
    "P1404": "Exhaust Gas Recirculation (EGR) Closed Position Performance",
    "P1405": "Exhaust Gas Recirculation System Valve 3",
    "P1406": "EGR Valve Pintle Position Circuit",
    "P1407": "EGR Air Intrusion in Exhaust Supply to EGR Valve",
    "P1408": "Intake Manifold Pressure Sensor Circuit",
    "P1409": "EGR Vacuum System Leak",
    "P1410": "Fuel Tank Pressure System",
    "P1415": "Secondary Air Injection (AIR) System Bank 1",
    "P1416": "Secondary Air Injection (AIR) System Bank 2",
    "P1418": "Secondary Air Injection System Relay A Control Circuit High",
    "P1420": "Intake Air Low Pressure Switch Circuit Low Voltage",
    "P1421": "Intake Air Low Pressure Switch Circuit High Voltage",
    "P1423": "Intake Air High Pressure Switch Circuit High Voltage",
    "P1441": "Evaporative Emission (EVAP) System Flow During Non-Purge",
    "P1442": "EVAP Vacuum Switch High Voltage During Ignition On",
    "P1645": "Evaporative Emission (EVAP) Vent Solenoid Control Circuit",
    "P1646": "Evaporative Emission (EVAP) Vent Solenoid Control Circuit",
    "P1655": "EVAP Purge Solenoid Control Circuit",
    "P1675": "EVAP Vent Solenoid Control Circuit",
    # Cooling fan / thermal
    "P1460": "Cooling Fan Control System / Misfire Detected With Low Fuel Level",
    "P1480": "Cooling Fan 1 Control Circuit High",
    "P1483": "Engine Cooling System Performance",
    "P1536": "Engine Coolant Overtemperature - Air Conditioning (A/C) Disabled",
    "P1660": "Cooling Fan Control Circuits",
    # Theft deterrent / security
    "P1500": "Starter Signal Circuit",
    "P1501": "Theft Deterrent System / Vehicle Speed Sensor Circuit Intermittent",
    "P1502": "Theft Deterrent Fuel Enable Signal Not Received",
    "P1503": "Theft Deterrent Fuel Enable Signal Not Correct",
    "P1504": "Vehicle Speed Output Circuit",
    "P1626": "Theft Deterrent Fuel Enable Signal Not Received",
    "P1629": "Theft Deterrent System - Cranking Signal",
    "P1630": "Theft Deterrent Learn Mode Active",
    "P1631": "Theft Deterrent Start Enable Signal Not Correct",
    "P1632": "Theft Deterrent Fuel Disable Signal Received",
    # Idle / throttle control (electronic throttle, IAC)
    "P1508": "Idle Speed Low - Idle Air Control (IAC) System Not Responding",
    "P1509": "Idle Speed High - Idle Air Control (IAC) System Not Responding",
    "P1510": "Throttle Control System Performance - Throttle Limitation Active",
    "P1511": "Throttle Control System - Backup System Performance",
    "P1514": "Airflow to TP Sensor Correlation High",
    "P1515": "Electronic Throttle System Throttle Position",
    "P1516": "Throttle Actuator Control (TAC) Module Throttle Actuator Position Performance",
    "P1517": "Electronic Throttle Module",
    "P1518": "Electronic Throttle Module to PCM Communication",
    "P1519": "Throttle Actuator Control (TAC) Module Internal Circuit",
    "P1523": "Throttle Closed Position Performance",
    "P1524": "Throttle Closed Position Performance",
    "P1525": "Throttle Body Service Required",
    "P1526": "Minimum Throttle Position Not Learned",
    "P1530": "Throttle Actuator Control (TAC) Module Internal Circuit",
    # A/C system
    "P1531": "A/C Low Side Temperature Sensor Fault",
    "P1532": "A/C Evaporator Temp. Sensor Circuit Low Voltage",
    "P1533": "A/C Evaporator Temp. Sensor Circuit High Voltage",
    "P1534": "A/C High Side Temp. Sensor Low Voltage",
    "P1535": "A/C High Side Temperature Sensor Circuit",
    "P1537": "A/C Request Circuit Low Voltage",
    "P1538": "A/C Request Circuit High Voltage",
    "P1539": "A/C Clutch Status Circuit High Voltage",
    "P1540": "Air Conditioning (A/C) Refrigerant Overpressure - Air Conditioning Disabled",
    "P1541": "A/C High Side Over Temperature",
    "P1542": "A/C System High Pressure High Temperature",
    "P1543": "A/C System Performance",
    "P1544": "A/C Refrigerant Condition Very Low",
    "P1545": "Air Conditioning (A/C) Clutch Relay Control Circuit",
    "P1546": "A/C Clutch Status Circuit Low Voltage",
    "P1547": "A/C System Performance Degraded",
    "P1548": "A/C Recirculation Circuit",
    # Cruise control
    "P1520": "Transmission Range Switch Circuit",
    "P1521": "Transmission Engaged at High Throttle Angle",
    "P1522": "Park/Neutral to Drive/Reverse at High RPM",
    "P1527": "Transmission Range to Pressure Switch Correlation",
    "P1528": "Governor",
    "P1529": "Heated Windshield Request Problem",
    "P1554": "Cruise Control Feedback Circuit",
    "P1555": "Electronic Variable Orifice Output",
    "P1558": "Cruise Control Servo Indicates Low",
    "P1559": "Cruise Control Power Management Mode",
    "P1560": "Transaxle Not in Drive - Cruise Control Disabled",
    "P1561": "Cruise Vent Solenoid",
    "P1562": "Cruise Vacuum Solenoid",
    "P1563": "Cruise Vehicle Speed/Set Speed Difference Too High",
    "P1564": "Vehicle Acceleration Too High - Cruise Control Disabled",
    "P1565": "Cruise Servo Position Sensor",
    "P1566": "Engine RPM Too High - Cruise Control Disabled",
    "P1567": "Active Banking Control Active - Cruise Control Disabled",
    "P1568": "Cruise Servo Stroke Greater than Commanded in Cruise",
    "P1569": "Cruise Servo Stroke High While not in Cruise",
    "P1570": "Traction Control Active - Cruise Control Disabled",
    "P1571": "Traction Control Torque Request Circuit",
    "P1572": "ASR Active Circuit Low Too Long",
    "P1573": "PCM/EBTCM Serial Data Circuit",
    "P1574": "Stoplamp Switch Circuit",
    "P1575": "Extended Travel Brake Switch Circuit",
    "P1576": "BBV Sensor Circuit High Voltage",
    "P1577": "BBV Sensor Circuit Low Voltage",
    "P1578": "BBV Sensor Circuit Low Vacuum",
    "P1579": "P/N to D/R at High Throttle Angle - Power Reduction Mode Active",
    "P1580": "Cruise Move Circuit Low Voltage",
    "P1581": "Cruise Move Circuit High Voltage",
    "P1582": "Cruise Direction Circuit Low Voltage",
    "P1583": "Cruise Direction Circuit High Voltage",
    "P1584": "Cruise Control Disabled",
    "P1585": "Cruise Control Inhibit Output Circuit",
    "P1586": "Cruise Control Brake Switch 2 Circuit",
    "P1587": "Cruise Control Clutch Control Circuit Low",
    "P1588": "Cruise Control Clutch Control Circuit High",
    "P1599": "Engine Stall or Near Stall Detected",
    # Module communication / serial data
    "P1600": "TCM Internal Watchdog Operation",
    "P1601": "Serial Communication Problem With Device 1",
    "P1603": "Loss of SDM Serial Data",
    "P1604": "Loss of IPC Serial Data",
    "P1605": "Loss of HVAC Serial Data",
    "P1606": "Serial Communication Problem With Device 6",
    "P1607": "Serial Communication Problem With Device 7",
    "P1608": "Serial Communication Problem With Device 8",
    "P1609": "Loss Of TCS Serial Data",
    "P1610": "Loss of PZM Serial Data",
    "P1611": "Loss of CVRTD Serial Data",
    "P1612": "Loss of IPM Serial Data",
    "P1613": "Loss of DIM Serial Data",
    "P1614": "Loss of RIM Serial Data",
    "P1615": "Loss of VTD Serial Data",
    "P1633": "Ignition 0 Switch Circuit",
    "P1634": "Ignition 1 Switch Circuit",
    "P1635": "5 Volt Reference Circuit",
    "P1636": "PCM Stack Overrun",
    "P1637": "Generator L-Terminal Circuit",
    "P1638": "Generator F-Terminal Circuit",
    "P1639": "5 Volt Reference 2 Circuit",
    "P1795": "CAN Bus - Throttle Body Position",
    # Module/ECM internal, oil life, misc sensors
    "P1617": "Engine Oil Level Switch Circuit",
    "P1619": "Engine Oil Life Monitor Reset Circuit",
    "P1620": "Low Coolant Circuit",
    "P1621": "Control Module Long Term Memory Performance",
    "P1622": "Cylinder Select",
    "P1623": "Transmission Temp Pull-Up Resistor",
    "P1624": "Customer Snapshot Requested - Data Available",
    "P1625": "TCM System Reset",
    "P1627": "A/D Performance",
    "P1628": "ECT Pull-Up Resistor",
    "P1640": "Driver-1-Input High Voltage",
    "P1641": "Malfunction Indicator Lamp (MIL) Control Circuit",
    "P1642": "Vehicle Speed Output Circuit",
    "P1643": "Engine Speed Output Circuit",
    "P1644": "Traction Control Delivered Torque Output Circuit",
    "P1647": "Driver 1 Line 7",
    "P1650": "Control Module Output B Circuit",
    "P1651": "Fan 1 Relay Control Circuit",
    "P1652": "Powertrain Induced Chassis Pitch Output Circuit",
    "P1653": "Oil Level Lamp Control Circuit",
    "P1654": "Cruise Control Inhibit Output Circuit",
    "P1656": "Driver 2 Line 6",
    "P1657": "1-4 Upshift Solenoid Control Circuit",
    "P1658": "Starter Enable Relay Control Circuit",
    "P1661": "MIL Control Circuit",
    "P1662": "Cruise Lamp Control Circuit",
    "P1663": "Oil Life Lamp Control Circuit",
    "P1664": "1-4 Upshift Lamp Control Circuit",
    "P1665": "Driver 3 Line 5",
    "P1666": "Driver 3 Line 6",
    "P1667": "Reverse Inhibit Solenoid Control Circuit",
    "P1669": "ABS Unit Expected",
    "P1670": "Driver 4",
    "P1671": "Driver 4 Line 1",
    "P1672": "Low Engine Oil Level Lamp Control Circuit",
    "P1673": "Engine Hot Lamp Control Circuit",
    "P1674": "Tachometer Control Circuit",
    "P1676": "Driver 4 Line 6",
    "P1677": "Driver 4 Line 7",
    "P1680": "Driver 5",
    "P1681": "Driver 5 Line 1",
    "P1682": "Driver 5 Line 2",
    "P1683": "Driver 5 Line 3",
    "P1684": "Driver 5 Line 4",
    "P1685": "Driver 5 Line 5",
    "P1686": "Driver 5 Line 6",
    "P1687": "Driver 5 Line 7",
    "P1689": "Delivered Torque Circuit Fault",
    "P1690": "ECM Loop Overrun",
    "P1691": "Coolant Gage Circuit Low Voltage",
    "P1692": "Coolant Gage Circuit High Voltage",
    "P1693": "Tachometer Circuit Low Voltage",
    "P1694": "Tachometer Circuit High Voltage",
    "P1695": "Remote Keyless Entry Circuit Low",
    "P1696": "Remote Keyless Entry Voltage High",
    # Transmission control (TCM)
    "P1700": "Transmission Control Module (TCM) Requested MIL Illumination",
    "P1701": "Trans. MIL Request Circuit",
    "P1705": "P/N Signal Output Circuit",
    "P1740": "Torque Reduction Signal Circuit",
    "P1743": "TP Signal from ECM",
    "P1760": "TCM Supply Voltage Interrupted",
    "P1779": "Engine Torque Delivered to TCM Signal",
    "P1780": "Park/Neutral Position (PNP) Switch Circuit",
    "P1781": "Engine Torque Signal Circuit",
    "P1790": "Transmission Control Module Checksum",
    "P1791": "Transmission Control Module Loop",
    "P1792": "Transmission Control Module Reprogrammable Memory / ECM to TCM Engine Coolant Signal",
    "P1793": "Transmission Control Module Stack Overrun",
    "P1800": "TCM Power Relay Control Circuit",
    "P1801": "Performance Selector Switch Failure",
    "P1804": "Ground Control Relay",
    "P1810": "TFP Valve Position Switch Circuit",
    "P1811": "Maximum Adapt and Long Shift",
    "P1812": "Transmission Over Temperature Condition",
    "P1813": "Torque Control",
    "P1814": "Torque Converter Overstressed",
    "P1815": "Transmission Range Switch - Start In Wrong Range",
    "P1816": "TFP Valve Position Switch - Park/Neutral With Drive Ratio",
    "P1817": "TFP Valve Position Switch - Reverse With Drive Ratio",
    "P1818": "TFP Valve Position Switch - Drive Without Drive Ratio",
    "P1819": "Internal Mode Switch - No Start/Wrong Range",
    "P1820": "Internal Mode Switch Circuit A Low",
    "P1822": "Internal Mode Switch Circuit B High",
    "P1823": "Internal Mode Switch Circuit P Low",
    "P1825": "Internal Mode Switch - Invalid Range",
    "P1826": "Internal Mode Switch Circuit C - High",
    "P1831": "PC Solenoid Power Circuit - Low Voltage",
    "P1833": "A/T Solenoids Power Circuit - Low Voltage",
    "P1835": "Kick-Down Switch Circuit",
    "P1836": "Kick-Down Switch Failed Open",
    "P1837": "Kick-Down Switch Failed Short",
    "P1842": "1-2 Shift Solenoid Circuit Low Voltage",
    "P1843": "1-2 Shift Solenoid Circuit High Voltage",
    "P1844": "Torque Reduction Signal Circuit Desired By TCM",
    "P1845": "2-3 Shift Solenoid Circuit Low Voltage",
    "P1847": "2-3 Shift Solenoid Circuit High Voltage",
    "P1850": "Brake Band Apply Solenoid Circuit",
    "P1851": "Brake Band Apply Solenoid Performance",
    "P1852": "Brake Band Apply Solenoid Low Voltage",
    "P1853": "Brake Band Apply Solenoid High Voltage",
    "P1860": "TCC PWM Solenoid Circuit Electrical",
    "P1864": "Torque Converter Clutch Circuit",
    "P1868": "Transmission Fluid Life",
    "P1870": "Transmission Component Slipping",
    "P1871": "Undefined Gear Ratio",
    "P1873": "TCC Stator Temp. Switch Circuit Low",
    "P1874": "TCC Stator Temp. Switch Circuit High",
    "P1875": "4WD Low Switch Circuit Electrical",
    "P1884": "TCC Enable/Shift Light Circuit",
    "P1886": "Shift Timing Solenoid",
    "P1887": "TCC Release Switch Circuit",
    "P1890": "ECM Data Input Circuit / Throttle Position Signal Input",
    "P1891": "Throttle Position Sensor PWM Signal Low",
    "P1892": "Throttle Position Sensor PWM Signal High",
    "P1893": "Engine Torque Signal Low Voltage",
    "P1894": "Engine Torque Signal High Voltage",
    "P1895": "TCM to ECM Torque Reduction Circuit",
}

ENHANCED_PIDS: tuple[EnhancedPID, ...] = (
    # EnhancedPID(pid="221E37", name="TRANS_FLUID_TEMP", description="Transmission fluid temperature", unit="°C"),
)


class GMProfile(VehicleProfile):
    key = "gm"
    display_name = "General Motors"
    wmi_codes = ("1G1", "1GC", "1GT", "3GN")

    def get_dtc_description(self, code: str) -> str | None:
        return DTC_TABLE.get(code)

    def enhanced_pids(self) -> tuple[EnhancedPID, ...]:
        return ENHANCED_PIDS


register_profile(GMProfile())
